from enum import Enum

class TransactionCategory(Enum):
    EATING = "Ăn uống"
    HOUSING = "Nhà ở"
    TRANSPORT = "Di chuyển"
    EDUCATION = "Giáo dục"
    GIFTS = "Quà tặng"
    BILLS = "Hóa đơn & Tiện ích"
    SHOPPING = "Mua sắm"
    BEAUTY = "Làm đẹp"
    FAMILY = "Gia đình"
    PETS = "Vật nuôi"
    HEALTH = "Sức khỏe"
    ENTERTAINMENT = "Giải trí"
    WORK = "Công việc"
    INSURANCE = "Bảo hiểm"
    OTHER = "Các chi phí khác"
    DEBT = "Trả nợ"
    SPORTS = "Thể thao"
    INVESTMENT = "Đầu tư"
    SALARY = "Lương"
    OTHER_INCOME = "Thu nhập khác"
    UNKNOWN = "Không xác định"
